### ISSUE TITLE
Multi percentiles

### ISSUE THREAD

**Issue by oneandonlyonebutyou** [d4rkr00t/percentile#101]
How am I efficiently get multiple percentiles

```js 
a = [1,2,3,4,....]
//getting 50,60,70 percentiles
percentile([50,60,70], a)

```
Since my data is very large, I wonder what would you suggest?
Thank you

**Comment by d4rkr00t** [comment]
Unfortunately `percentile` always sorts an array, but this sounds like a good feature request. I'll try and have a look at implementing this, sometime this week.
