### ISSUE TITLE
It does not work properly for some extreme cases

### ISSUE THREAD

**Issue by nskazki** [d4rkr00t/percentile#19]
version: `percentile@1.0.0`

```
> percentile(undefined, [1,2,3,4,5,6])
undefined
> percentile(-100, [1,2,3,4,5,6])
undefined
> percentile(-10, [1,2,3,4,5,6])
undefined
> percentile(-1, [1,2,3,4,5,6])
undefined
> percentile(0, [1,2,3,4,5,6])
undefined
> percentile(110, [1,2,3,4,5,6])
undefined
```

**Comment by d4rkr00t** [comment]
Hi, thanks for the report. 

What do you expect get from percentile with this params? An error?

**Comment by nskazki** [comment]
for exceptional cases - yes, of course, you need to throw an exception:
- percentile(-1, ...)
- percentile(101, ...)
- percentile(100, [ 1,    , 3,    , 5, 6 ])
- ...

for extreme cases - I think you need to add a few checks:
-  percentile(0, [1,2,3,4,5,6]) -> if p == 0 then return list[0]
-  percentile(100, [1,2,3,4,5,6]) -> if p == 100 then return list[list.length-1]

**Comment by d4rkr00t** [comment]
Sounds good to me :). I'll do it as soon as i can :)
