### ISSUE TITLE
Passed array gets sorted in place

### ISSUE THREAD

**Issue by jjnp** [d4rkr00t/percentile#98]
I just noticed that the array with the values passed gets sorted in place, and that this is undocumented behaviour, which can cause problems if you don't expect the passed array to be sorted afterwards.
Simple fix is to pass it via, so that a copy is created beforehand:
`percentile(50, myArray.slice(0))`
I'll submit a PR for it myself if I get around to it...

**Comment by d4rkr00t** [comment]
Released in: https://github.com/d4rkr00t/percentile/releases/tag/v1.2.2
